sudo: required

services:
  - docker

env:
  global:
    - VERSION=3.0.5.19020701
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=syspass
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=syspass
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/syspass/VYgBuOxIs5c78m3sHrXZnM8K6o0=
    - secure: FY0dzByGWqETL4VdUtqULHE8/WOQDFjhYV62zALO6ZNN9GRFfkXS0mWa3H2rmmPfJ/njpqcBiXcM/TOEJwiAKItoNAhAWT2ty9Rihc6/TwSwd95uT0w1Ah+vWhJLC/hOBiXsPz74wockfyJCH8+JNPmVQqS4BxWFGRFjSB3OxLGwwg7RqBG9xzshu9+1geCH+9RbVGScYb7c7yoKHxhtiWzXL/oEgQCrXO6TNZ6eIsquhofbM5TtTFBM5X9F2Zu8RT44GXIUacoxwca5LnvQETVcaN8pTN0YrJ3JX45QfUX2HFREOk6UIMbRTkkSMILoju76BBrWenF8X8N2eDlajIKs+mxaayHqLflOgJXzrCMzdctC0AvkhqzhZcO07rKugYWU2O+UMH3Rj4m2VuPX6xx8mBEAN1GLW/+b9cDqLjOZWnENgbCkIn3C/CnPtUKpl8Jvz3YIqIZCZUVrBoDiFUkbo99oZU4xSPWanj82ibYrrJCG6udrVd+yV2UCQruezjvWB9CtnnCDN3AjXTezNWTp672+05z/ULx+v9h9MNXpre7B+Zn2Xg/aybvTcwPuCNkSfh/JQ+GtewP8END+LtB6GCTIQD5PMYGvZV52H+y+oNz8e+jCdjytY6JTVHUw2r5kdwNNinT68a2BaEcSUOew+dxk/oAZGsfvV2CAdeA= # DOCKER_PASSWORD
    - secure: xH1uxln8ve4h/zDgiLZrmIUl3tsQUmCilYzfxhuOlrmUzaJVxxR9q0cGZErKyBhxFEQ12GBjIJC4S/BDPL8BpnCtHO2ObZMNqYNAlQCsugwLR86lG8TkOjwprIHRnGVWhrcnzhG5jcO67kDQOrQzifkLRCuiouT1YKfqxpfiFIeIjqnFdixuG/XBk5tIqo4bQ7/WcO1RTElv7ldddcJd1lF6d1D+qfyoy331KSm14IVLUoBaDki6vqNPpriQS1meHPwPTOu2M5haf6wAf3TAMptxGVixIo0O32soVha6hlQODUuDq4C/ulQMWdo7lSKt9Nt+GfpyCsQ8NGuXwWlZ/3Fgf/wfjl2E5SQa2wZHa58Qbcw2/zo+/8cdHHlRupo3a6emIjlpEpgL789hLzNJzRwomuLqjZnIc+tXPWQ0AHT2O4+MJUCCeSiyamr7OT+Bl+wHgNI1HwQbPs3HSGiYENYCo1mzj7bJPqfT0vgKaFfoqqNrYm3Pvv33ILvmldatVFOj0xB1IERj/b74q2y+gBu3liDqfWMTYF3ZI7BLI/WraOcOOP73NYsME8IdFgT/w51P6SLB/3QKXiEZJ3I7MlmZXmvmQE7YXEB5IF8t5b0tSlLSgnpXqCRAvXMkcQGgv/mdT+gHPqVIEBRUkyOTS6DAFkk88MQn/w5I0uuFAKQ= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
